language: bash

services: docker

os: windows

before_script:
  - docker version
  - env | sort

script:
  - |
    (
      set -Eeuo pipefail
      set -x

      # build:
      docker build --tag rocker-win:1803-latest --file 1803/latest/Dockerfile .
      
      # test:
      docker run --rm rocker-win:1803-latest R.exe --version
      docker run --rm rocker-win:1803-latest Rscript.exe -e "sessionInfo()"
    )

after_script:
  - docker images
