language: bash
services: docker
os: windows
env:
  global:
  - secure: ebi0TzaxCa+/lBGZgAboRtuP6OBbIJeYho5I2DiQlsYJGGuqO+jSPRfx4n5wdpxepsJrciIl7m9DUwLkV9UEd8iUYNmaE3wPiHDiAlKgUu2Tcrqlw64JdY9OxvU0/dJhgriN1W0NdDRVG82mjvnttG+1/xywUXqcbcNEB2EEABos7KsutTW47+6/m1W1maDs8MO08EmcGZV1qpjwIroaVe92zGsqd9kX1AzRAT6nKR8RmrA4Xloxgq3C0yQtJsBLCq/Qj4wvw9NNNfspdLiZuIjmJw+Vlut/o3pms8T5bs7ikAHA/qvUHfBTMO0ieDND556QqTJlLIa7AuizE/5u6x3A6Ke8H9GWcT/KuMKhA2Nk1MseHrVWUkOcZPJuR+5/EZh731h14cyGyMb1tMEBaSKb+1XIlfkS9hG0z/tljZjrtKOMahQ7J1VEQnEi/vja2rRUP8t09TLygVvI403SfLV40llDKs0pZwihCsA5hANrdqxOa+eK3mcj9XO68ymOVMTIcjyC7lw/l7skPu5kkBLpRLywtwaQbLdDQxYfQHkmo0ZnbZl3kLnxgldmsi3XuuR0UxUDYijP0E3wI+TI8WAy1AceeaJoQyC4K770aprYCWmUST8t0lT2DDhJfBJ92lLmZuFRn3GRLtrEXgt5SOjK8j+XAv3QIBJzRCsk+MU=
  - secure: GJF7VkK2MR1tI+R47UF9t+UAdB9F5PKBeJKL+J2vYNNfgB398piqD9Xf5Ck17cB3W8btmx4DKUqhMh9e3i4WAyXSLad6Qo6Wuk06ninSKCvmzf35BKvr8g6NeYQUDndKM18ty63nvaa/ZKozS7Hnm5kCIbPYhkpgAWOOlwgVU3hbX+xpVEIrWSVWnnu/V2LYamtVDqeX7VGm7qHJKX3KxrqZHuXco6cWyxm4hcJ0Dt/NBFql3mpL/QbpI7ySI1yp/yf8OA62YBnQrbDV+fDzBAi4MLf5tHdwZJGLX+GGDjx47y/Z9hUjUPyf/MB3CvvAyhKSSt2MI8QY60ez0qVwn27GYJyrN4tlknfI4Q7qU0DK3w6nN6b6UbLvkbTbW0KrXXOnhxHM988vGuI31ALBU90/9mbYHW2BKyYSDLjOPdw++q2voaelNzH7JsPlNxGi0pyLTIwFF5qFwmZp4MvmzsAeYn/u/CKo8KjAyKOnc7h7isZObA2/N1/nTqPvCFTjiBbna4rpY5tHkOkkad6F/iYN3+20RboM/J3o8J3WVFKquoQNb8n6uwtLg5li+8d0pIm1a7ksffhd9PQuV8hWegX/xgdUcRdF3zaswLqr2FToxtMXdyC7Z6YFu82jTrxRVJTIocKmx5muczBwsxbNUEnjlDzcvYnmnggOj5hMfBM=
jobs:
  include:
  - env: R_VERSION=3.5.3
  - env: R_VERSION=3.6.2
  - env: R_VERSION=latest
before_script:
- docker version
- env | sort
script:
  - |
    (
      set -Eeuo pipefail
      set -x
      
      echo Building $R_VERSION
      docker build --tag rocker-win:1803-$R_VERSION --file 1803/$R_VERSION/Dockerfile .
    )
  - |
    (
      set -Eeuo pipefail
      set -x
      
      echo Testing $R_VERSION
      docker run --rm rocker-win:1803-$R_VERSION Rscript.exe -e "sessionInfo()"
    )
  - |
    (
      set -Eeuo pipefail
      set -x

      echo Pushing $R_VERSION
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      docker tag rocker-win:1803-$R_VERSION nuest/rocker-win:1803-$R_VERSION
      docker push nuest/rocker-win:1803-$R_VERSION
    )
after_script:
- docker images
